version: "3.9"

services:

  api:
    container_name: api
    build:
      context: ./api-python
    networks:
      - tech-test-net
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=1
    volumes:
      - ./api-python:/api
      - ./data:/data

  client:
    container_name: client
    build:
      context: ./client
    volumes:
      - ./client/public:/client/public
      - ./client/src:/client/src
      - ./client/package.json:/client/package.json
      - ./client/package-lock.json:/client/package-lock.json
    ports:
      - 3000:3000
    networks:
      - tech-test-net
    stdin_open: true
    environment:
      - REACT_APP_WITHIN_DOCKER=true

networks:
  tech-test-net:
    driver: bridge
